課題の確認をお願いします
Junkichi89/ToDoList-New pull request #1
Opened 2020-07-07 12:51 UTC by Junkichi89

2020-07-07 13:17 UTC, myzktkyk requested changes
動作としては問題ありません！
ただ現在の実装の方法ですと、タスク状態変更機能など
今後様々な機能を追加する際に苦労することになります。

なので、今のうちに以下のような実装方法に変更しましょう！

1. 入力されたタスク内容とその状態（デフォルトでは作業中）をオブジェクトで管理する
2. 上記のオブジェクトをはtodosという名前の配列に追加することで、複数のタスクを管理する。
3. todo配列の内容を表示させる関数（displayTodos）を定義する

オブジェクトの内容は以下のような感じになります。

```
todo = {
            task: '入力されたタスク'
            status: '作業中'
       }

```

タスクが入力される度に、この todo オブジェクトを todos という配列にpushし
タスクを保存していく感じです！

2020-07-07 13:27 UTC, kouki-iwahara commented on js/main.js
> +  function con_btn() {
この関数で作成されたボタンをinp_taskの中で発火させ、returnで受け取ると今後の実装がしやすいかと思います。
del_btn()も同様です。

2020-07-07 13:27 UTC, kouki-iwahara commented on js/main.js
> +    let input = text.value;
todoの情報をもつオブジェクトを作成し、そのオブジェクトを配列にpushする実装が良いでしょう。
オブジェクトは以下のイメージです。
const todo = {
  content: 'todoのコメント'
  state: '作業中'
}

2020-07-07 13:27 UTC, kouki-iwahara commented on js/main.js
> +   function inp_task () {
jsで単語の繋ぎは_ではなくinpTaskのようにキャメルケースで記述しましょう！
また、input taskの意味だと思いますが、実行している内容と関数名の不一致が気になります。

2020-07-07 13:28 UTC, kouki-iwahara commented on css/styles.css
> +#btn {
cssはidではなくclassを指定して記述しましょう^^

2020-07-07 13:29 UTC, kouki-iwahara commented on js/main.js
> +    inpEl_con.setAttribute("class","inp_con");
,の後ろにはスペースを空けましょう。

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +let i = 0;
iだけだとどんな変数か想像しにくいので、長くてもちゃんとした命名にしましょう

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +  let textValue = text.value;
一箇所しか使用されていないので、変数化せずそのまま代入しても大丈夫です

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +    for (let i = 0; i < todos.length; i++){
)と{の間には半角スペースを入れましょう

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +            tdNum.innerHTML = `${i}`;
インデントがズレています

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +  const displayTodos = function() {
functionはアロー関数に置き換えましょう
参考
https://qiita.com/may88seiji/items/4a49c7c78b55d75d693b

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +          };
for文の最後にはセミコロンは不要です

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +        const tdStatus = document.createElement('td');
インデントがズレています

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +    function statusBtn() {
functionはアロー関数に置き換えましょう
参考
https://qiita.com/may88seiji/items/4a49c7c78b55d75d693b

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +        delBtn.textContent = "削除";
"と'が混在しているので、特別な理由がない限り統一しましょう

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +        return statusBtn(), delBtn();
返り値があるのに使われていないようです

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +
不要な改行です

2020-07-09 12:35 UTC, Dok1211 commented on js/main.js
> +
不要な改行です

2020-07-14 14:17 UTC, merged